[package]
name = "lispoggers"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"] # ["cdylib"]
name = "kekw"
path = "Kekw/lib.rs"

[[bin]]
name = "kekw-main"
path = "Kekw/main.rs"

[dependencies]
regex = "1.11.1"
