name: Kekw Action CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install dependencies
        run: nix develop
      - name: Build project
        run nix develop --command cargo build
      - name: Run tests
        run: nix develop --command cargo test
